name: "한전 파워플래너"
version: "0.1.3"
slug: "kepco_power_planner"
description: |
  한전 파워플래너에서 데이터를 가져오는 애드온입니다.
  고객번호가 여러개 있을 경우 모두 센서로 등록됩니다.
  태양광 발전기가 설치되어있는 경우 발전량과 상계후 요금도 함께 가져옵니다.
  고유ID 는 현재 지원하고 있지 않습니다.
logo: true
arch:
  - "aarch64"
  - "amd64"
  - "armhf"
  - "armv7"
  - "i386"
init: false
api: true
hassio_api: true
homeassistant_api: true
options:
  RSA_USER_ID: ""
  RSA_USER_PWD: ""
  update_interval: 30
schema:
  RSA_USER_ID: "str"
  RSA_USER_PWD: "password"
  update_interval: "int(1,)"